import { useMemo, useState } from 'react';
import { marked } from 'marked';
import calibrationMd from '../generated/calibration.md?raw';

/**
 * Calibration evidence from the engine backtest (engine/reports/, copied by `npm run sync`).
 * The markdown is repo content generated by our own backtest, rendered as-is.
 */
export function Model() {
  const html = useMemo(() => (calibrationMd.trim() ? (marked.parse(calibrationMd, { async: false }) as string) : ''), []);
  const [svgOk, setSvgOk] = useState(true);
  return (
    <>
      <div className="page-head">
        <div>
          <h1>Pricing model and evidence</h1>
          <p>
            The premium is a probability times the payout. This page shows the formula, and the backtest that checks the probability against what
            Hyperliquid prices actually did.
          </p>
        </div>
      </div>
      <div className="grid grid--model">
        <section className="panel">
          <div className="panel__head">
            <h2>Reliability plot</h2>
            <span className="meta">engine/reports/calibration.svg</span>
          </div>
          {svgOk ? (
            <div className="figure">
              <img src="/calibration.svg" alt="Calibration: predicted touch probability against realized touch frequency per bucket" onError={() => setSvgOk(false)} />
            </div>
          ) : (
            <p className="empty">No calibration plot found. Run the engine backtest, then `npm --prefix app run sync`.</p>
          )}
        </section>
        <section className="panel">
          <div className="panel__head">
            <h2>Formula (ARCHITECTURE §7)</h2>
          </div>
          <div className="formula">
            {`S  = pool price source oraclePx6 (= spotRef)
σ  = max(EWMA λ=0.94 of 1h log returns,
         30-day realized), annualized
T  = duration in years;  b = ln(L/S);  s = σ√T
p  = one-touch probability, driftless GBM
     down: N((b + s²/2)/s) + (S/L)·N((b − s²/2)/s)
z  = b / s                  (distance in σ)
k, q = backtest table at |z|  (pooled buckets)
priced  = max(p·k, q);  refuse if > 0.5
premium = ceil(payout × priced × (1 + θ)) + fee
θ = 0.20`}
          </div>
          <p className="small soft" style={{ marginTop: 10 }}>
            k ≥ 1 scales the model where history shows more touches than it predicts; q is an empirical floor (a 95 % upper bound on the realized touch
            frequency at that distance in σ), so far-away levels never price at zero. Every quote shows its own S, σ, z, p, k and q, and the app recomputes
            the premium from them.
          </p>
        </section>
      </div>
      <section className="panel" style={{ marginTop: 16 }}>
        <div className="panel__head">
          <h2>Backtest report</h2>
          <span className="meta">engine/reports/calibration.md</span>
        </div>
        {html ? (
          <div className="prose" dangerouslySetInnerHTML={{ __html: html }} />
        ) : (
          <p className="empty">No calibration report bundled. Run the engine backtest, then `npm --prefix app run sync`.</p>
        )}
      </section>
    </>
  );
}
