import { useMemo, useState } from 'react';
import { marked } from 'marked';
import calibrationMd from '../generated/calibration.md?raw';
import { modelText } from '../lib/calibration';

/**
 * Calibration evidence from the engine backtest (engine/reports/, copied by `npm run sync`).
 * The markdown is repo content generated by our own backtest, rendered as-is.
 */
export function Model() {
  const html = useMemo(() => (calibrationMd.trim() ? (marked.parse(calibrationMd, { async: false }) as string) : ''), []);
  // Formula and method text come from the synced calibration report, so they follow the engine.
  const m = useMemo(() => {
    const t = modelText(calibrationMd);
    const md = (x: string) => (x ? (marked.parseInline(x, { async: false }) as string) : '');
    return { ...t, lookupHtml: md(t.lookup), adoptedHtml: md(t.adopted), perBucketHtml: md(t.perBucket) };
  }, []);
  const [svgOk, setSvgOk] = useState(true);
  return (
    <>
      <div className="page-head">
        <div>
          <h1>Pricing model and evidence</h1>
          <p>
            The premium is a probability times the payout. This page shows the formula, and the backtest that checks the probability against what
            Hyperliquid prices actually did.
          </p>
        </div>
      </div>
      <div className="grid grid--model">
        <section className="panel">
          <div className="panel__head">
            <h2>Reliability plot</h2>
            <span className="meta">engine/reports/calibration.svg</span>
          </div>
          {svgOk ? (
            <div className="figure">
              <img src="/calibration.svg" alt="Calibration: priced touch probability against realized touch frequency" onError={() => setSvgOk(false)} />
            </div>
          ) : (
            <p className="empty">No calibration plot found. Run the engine backtest, then `npm --prefix app run sync`.</p>
          )}
        </section>
        <section className="panel">
          <div className="panel__head">
            <h2>Formula</h2>
            <span className="meta">{m.title ? `engine/reports/calibration.md · ${m.title}` : 'engine/reports/calibration.md'}</span>
          </div>
          {m.formula ? (
            <div className="formula">{m.formula}</div>
          ) : (
            <p className="empty">No pricing formula in the bundled report. Run the engine backtest, then `npm --prefix app run sync`.</p>
          )}
          {m.adoptedHtml && <p className="small soft" style={{ marginTop: 10 }} dangerouslySetInnerHTML={{ __html: m.adoptedHtml }} />}
          {m.perBucketHtml && <p className="small soft" style={{ marginTop: 10 }} dangerouslySetInnerHTML={{ __html: m.perBucketHtml }} />}
          {m.lookupHtml && <p className="small soft" style={{ marginTop: 10 }} dangerouslySetInnerHTML={{ __html: m.lookupHtml }} />}
          <p className="small soft" style={{ marginTop: 10 }}>
            Every quote shows its own S, σ, z, p, k and q, and the app recomputes the premium from them.
          </p>
        </section>
      </div>
      <section className="panel" style={{ marginTop: 16 }}>
        <div className="panel__head">
          <h2>Backtest report</h2>
          <span className="meta">engine/reports/calibration.md</span>
        </div>
        {html ? (
          <div className="prose" dangerouslySetInnerHTML={{ __html: html }} />
        ) : (
          <p className="empty">No calibration report bundled. Run the engine backtest, then `npm --prefix app run sync`.</p>
        )}
      </section>
    </>
  );
}
