#!/usr/bin/env node
// Regenerates the app's committed inputs from the rest of the repo:
//   src/generated/abi.ts          minimal typed ABIs from contracts/out (run `forge build` first)
//   src/generated/deployments.ts  deployments/testnet.json as a typed constant
//   src/generated/calibration.md  + public/calibration.svg   engine calibration evidence (if present)
// Output is committed so `npm run build` works without forge or the engine. Run: `npm run sync`.
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repo = path.resolve(appDir, '..');
const outGen = path.join(appDir, 'src', 'generated');
mkdirSync(outGen, { recursive: true });

const header = '// GENERATED by app/scripts/sync.mjs — do not edit by hand.\n';

// ---------------------------------------------------------------- ABIs
const contracts = [
  ['CoverPool', 'CoverPool.sol/CoverPool.json'],
  ['MockUSDC', 'MockUSDC.sol/MockUSDC.json'],
  ['MockPriceSource', 'MockPriceSource.sol/MockPriceSource.json'],
  ['MockPositionSource', 'MockPositionSource.sol/MockPositionSource.json'],
  ['IPriceSource', 'IPriceSource.sol/IPriceSource.json'],
  ['HyperCorePriceSource', 'HyperCorePriceSource.sol/HyperCorePriceSource.json'],
  ['HyperCorePositionSource', 'HyperCorePositionSource.sol/HyperCorePositionSource.json'],
];
const outDir = path.join(repo, 'contracts', 'out');
if (existsSync(outDir)) {
  let ts = header + '/* eslint-disable */\n';
  for (const [name, rel] of contracts) {
    const file = path.join(outDir, rel);
    if (!existsSync(file)) throw new Error(`missing ${file} — run forge build in contracts/`);
    const abi = JSON.parse(readFileSync(file, 'utf8')).abi;
    ts += `\nexport const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  }
  writeFileSync(path.join(outGen, 'abi.ts'), ts);
  console.log(`[sync] abi.ts (${contracts.length} contracts)`);
} else {
  console.log('[sync] contracts/out missing — kept existing abi.ts');
}

// ---------------------------------------------------------------- deployments
const depFile = path.join(repo, 'deployments', 'testnet.json');
const dep = JSON.parse(readFileSync(depFile, 'utf8'));
writeFileSync(
  path.join(outGen, 'deployments.ts'),
  header + `export const testnet = ${JSON.stringify(dep, null, 2)} as const;\n`,
);
console.log('[sync] deployments.ts');

// ---------------------------------------------------------------- calibration evidence
// NUMERA_REPORTS_DIR wins when given (e.g. a newer engine branch); else this checkout's engine/reports.
const reportDirs = [process.env.NUMERA_REPORTS_DIR, path.join(repo, 'engine', 'reports')].filter(Boolean);
const reports = reportDirs.find((d) => existsSync(path.join(d, 'calibration.svg')));
if (reports) {
  mkdirSync(path.join(appDir, 'public'), { recursive: true });
  copyFileSync(path.join(reports, 'calibration.svg'), path.join(appDir, 'public', 'calibration.svg'));
  const md = existsSync(path.join(reports, 'calibration.md')) ? readFileSync(path.join(reports, 'calibration.md'), 'utf8') : '';
  writeFileSync(path.join(outGen, 'calibration.md'), md);
  console.log(`[sync] calibration.svg/.md from ${reports}`);
} else {
  if (!existsSync(path.join(outGen, 'calibration.md'))) writeFileSync(path.join(outGen, 'calibration.md'), '');
  console.log('[sync] no calibration report found — Model page shows a placeholder');
}
